### PR TITLE
Webdam 72 style asset browser

### PR DESCRIPTION
**Pull request by briwagner**

### CODE REVIEW

**Comment by briwagner** [comment]
This is best I can do for tomorrow. Full-screen, this is solid. Going forward, I don't know how durable this will be, i.e. responsive. The sticky footer doesn't behave perfectly. We'll have to make some changes to markup to make the folders and images appear in line in the grid. It's not CSS to make that work; or not good CSS. 

Also I think the module returns 10 items. If we want a pretty grid, it should return nine or 12 or whatever is a multiple of three or four. Or however many items we want in a row. I took the easy route and kept it to a row of three, as before.

**Comment by cweagans** [comment]
There are a few notices coming out of this + the select assets button seems to be missing entirely. In addition, the folders are not in line with the assets. Seems like there's still some work left to do here, so I'm going to leave it unmerged for the time being. We can come back to it after the demo.

**Comment by cweagans** [comment]
There are some conflicts here. Can you work with @jasonschulte to resolve them and then we can merge tomorrow?

**Comment by cweagans** [comment]
@jasonschulte @briwagner I dealt with the conflicts here. Can you double check 4922f8b to make sure everything looks right?

**Pull request merged**
