### PR TITLE
8.x 1.x acquiadam rename

### PR DESCRIPTION
**Pull request by anairamzap-mobomo**
Finish the renaming for the missing bits:
- Routing for Controller
- Class Name in services file
- ClientFactory class namespace

And finally, modified the travis config file to match the new directory name 'media_acquiadam' so hopefully the build passes.

### CODE REVIEW

**Comment by cweagans** [comment]
Looks like there are some conflicts here.

**Comment by anairamzap-mobomo** [comment]
Removed those two config files from lighting to solve conflicts

**Comment by anairamzap-mobomo** [comment]
Closing this PR as I was working on an outdated branch. The only rename missing was in README file for the travis build state image.

**Comment by cweagans** [comment]
Ah, yeah, that'd do it. Feel free to change the README if necessary.

**Pull request closed without merging**
